all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_user: vagrant
    ansible_become_pass: vagrant
    ansible_python_interpreter: /usr/bin/python3

  hosts:
    node01:
      ansible_host: 10.10.10.101
      ansible_ssh_private_key_file: .vagrant/machines/node01/libvirt/private_key
    node02:
      ansible_host: 10.10.10.102
      ansible_ssh_private_key_file: .vagrant/machines/node02/libvirt/private_key
    node03:
      ansible_host: 10.10.10.103
      ansible_ssh_private_key_file: .vagrant/machines/node03/libvirt/private_key
    node04:
      ansible_host: 10.10.10.104
      ansible_ssh_private_key_file: .vagrant/machines/node04/libvirt/private_key



k3s_cluster:
  vars:
    k3s_release_version: v1.29
    k3s_become: true
    k3s_registries:
      mirrors:
        "docker.local":
          endpoint:
            - "http://docker-registry-service:5000"
  children:
    k3s_server:
      hosts:
        node01:

    k3s_agent:
      hosts:
        node02:
        node03:
        node04:


