---
- hosts: k3s_server[0]
  gather_facts: no
  become: yes

  tasks:
  - name: Copy kubeconfig file
    copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: /tmp/k3s.yaml
      remote_src: yes
  - name: Replace occurrences of 127.0.0.1 with host IP
    replace:
      path: /tmp/k3s.yaml  # Adjust the filename
      regexp: '127.0.0.1'
      replace: "{{ ansible_host }}"
  - name: Copy kubeconfig from control node to local.
    fetch:
      src: /tmp/k3s.yaml
      dest: ../../k3s.yaml
      flat: yes

