---
- name: Build a cluster with a single control node
  hosts: k3s_cluster
  vars:
    k3s_become: true
    k3s_agent:
      node-name: "{{ inventory_hostname }}"
      with-node-id: true
  roles:
    - role: xanmanning.k3s

